steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.prod', '-t', 'us-central1-docker.pkg.dev/agr-asistente-openai-v1/repo-asistente-openai-agr-v2/image-asistente-openai-agr-v2:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/agr-asistente-openai-v1/repo-asistente-openai-agr-v2/image-asistente-openai-agr-v2:latest']
